name: reuse workflow example
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: name of the artifact
        required: false
        default: dist
        type: string
    # secrets:
    #   password:
    #     required: true
    outputs:
      result:
        description: your result name
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-slim
    steps:
      - name: get artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: list artifact name
        run: ls
      - name: set the outputs
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
        